name = "c"
main = "./src/index.js"
compatibility_date = "2026-09-15"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
html_handling = "none"

[[kv_namespaces]]
binding = "REPORTS_KV"
id = "fa035ad809cc4035a4debf7181d5c239"
